name: Update all lists
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update dependencies
      run: |
        rm doh_server_urls.list doh_server_domains.list ipv4.list ipv6.list nftables-ipv4.set nftables-ipv6.set
        python scrape_doh.py > doh_server_urls.list
        bash url-to-domains.sh
        bash dns-to-ip.sh 1.1.1.1
    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "auto update lists"
        branch: actions/update-lists
        title: Update lists
        body: Updated lists
        delete-branch: true
        labels: actions
