name: Update all lists
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt -yy update
        sudo apt -yy install python3-pip bind9-dnsutils
        sudo pip3 install aggregate6
        
    - name: Scrape DOH
      run: |
        python scripts/scrape_doh.py > doh_server_urls.list
        
    - name: Convert to domainlist
      run: |
        bash scripts/url-to-domains.sh

    - name: Scrape other lists
      run: |
        bash scripts/scrape_other_lists.sh

    - name: Resolve domains
      run: |
        bash scripts/dns-to-ip.sh 1.1.1.1
   
    - name: Create sets
      run: |
        bash scripts/create-sets.sh
   
#    - name: Create PR
#      uses: peter-evans/create-pull-request@v5
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        commit-message: "auto update lists"
#        branch: actions/update-lists
#        title: Update lists
#        body: Updated lists
#        delete-branch: true
#        labels: actions
#        signoff: true

# Commit all changed files back to the repository

    - name: Update Repo
      uses: stefanzweifel/git-auto-commit-action@v4
      commit_message: auto update lists
      commit_options: '--no-verify --signoff'


